- name: Setup redis yum repo
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install redis
  ansible.builtin.yum:
    name: redis
    state: Installed

- name: update redis config - listen address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 127.0.0.1
    replace: 0.0.0.0

- name: start redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes