- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDB Configuration - Upload Listen Address
  ansible.builtin.replace:
    path: /etc/mongodb.repo
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB Service
  ansible.builtin.systemd:
    name: mongodb
    state: started
    enabled: yes

- name: Download and extract MongoDB Schema
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Load Catalogue Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes

- name: Load users Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes