- name: Play Level Variables
  hosts: all
  vars:
    URL: play.sample.com
  tasks:
    name: Print URL
    ansible.builtin.debug:
      msg: URL {{URL}}

# if we declare a variable on play level then all the tasks can access that variable.

- name: Play level variables from a file
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}