- name: condition
  hosts: localhost
  vars:
    a: abc
    b: 10
    c: true
    d: false
  tasks:
    - name: condition on Strings
      debug:
        msg: String condition is true
      when: a == "abc"
    - name: condition on String 1
      debug:
        msg: String condition is not True
      when: a != "abc"
#quote strings
    - name: Number 1
      debug:
        msg: both number are equal
      when: a == 10
    - name: Number 2
      debug:
        msg: b is less than 20
      when: b < 20

    - name: Boolean 1
      debug:
        msg: c is true
      when: c
    - name: Boolean 2
      debug:
        msg: D is false
      when: not d