- name: Configure YUM repos
  ansible.builtin.shell: curl -fsSL https://rmp.nodesource.com/setup_lts.x | bash -

- name: Install Nodejs
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Setup App User, Dowload and Extract {{COMPONENT}} content
  include_role:
    name: common
    tasks_from: download

- name: Install NodeJs dependencies
  ansible.builtin.shell: mvn clean package target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/roboshop/{{COMPONENT}}/
  become_user: roboshop

- name: Setup Systemd
  include_role:
    name: common
    tasks_from: download