- name: Configure YUM repos
  ansible.builtin.shell: curl -fsSL https://rmp.nodesource.com/setup_lts.x | bash -

- name: Install Nodejs
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Setup App User, Dowload and Extract {{COMPONENT}} content
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install NodeJs dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
    state: present
  become_user: roboshop

- name: Setup Systemd
  ansible.builtin.include_role:
    name: common
    tasks_from: download