- name: Install Maven
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: present

- name: Setup App User, Dowload and Extract {{COMPONENT}} content
  include_role:
    name: common
    tasks_from: download

- name: Install python dependencies
  pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Print
  debug:
    msg: "{{APP_USER_REGISTER}}"

- name: Update USER ID in App Configuration
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line: uid = {{APP_USER_REGISTER.uid}}

- name: Update GROUP ID in App Configuration
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid'
    line: gid = {{APP_USER_REGISTER.group}}


- name: Setup Systemd
  include_role:
    name: common
    tasks_from: download