#If any task is changed and if we want to run another task then handlers comes into picture.
#By default handlers run at the ending of the play, this behaviour can be changed as well and will run immediately

- name: Restart Nginx
  ignore_errors: "{{CHECK_MODE}}"
  ansible.builtin.systemd:
    name: nginx
    state: restarted